export type IconCategory = 'all' | 'home' | 'cleaning' | 'repair' | 'beauty' | 'tech' | 'health' | 'auto' | 'other';

export type IconLibrary = 'all' | 'solar' | 'hugeicons' | 'mdi' | 'lucide' | 'tabler' | 'phosphor';

export type ServiceIconOption = {
  icon: string;
  category: Exclude<IconCategory, 'all'>;
  library: Exclude<IconLibrary, 'all'>;
  label: string;
};

export const SERVICE_ICON_CATEGORIES: { id: IconCategory; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'home', label: 'Home' },
  { id: 'cleaning', label: 'Cleaning' },
  { id: 'repair', label: 'Repair' },
  { id: 'beauty', label: 'Beauty' },
  { id: 'tech', label: 'Tech' },
  { id: 'health', label: 'Health' },
  { id: 'auto', label: 'Auto' },
  { id: 'other', label: 'Other' },
];

export const SERVICE_ICON_LIBRARIES: { id: IconLibrary; label: string }[] = [
  { id: 'all', label: 'All Libraries' },
  { id: 'solar', label: 'Solar' },
  { id: 'hugeicons', label: 'Hugeicons' },
  { id: 'mdi', label: 'Material Design' },
  { id: 'lucide', label: 'Lucide' },
  { id: 'tabler', label: 'Tabler' },
  { id: 'phosphor', label: 'Phosphor' },
];

const solarIcons: ServiceIconOption[] = [
  { icon: 'hugeicons:legal-hammer', category: 'repair', library: 'hugeicons', label: 'Category Default' },
  { icon: 'solar:box-minimalistic-linear', category: 'other', library: 'solar', label: 'Service Default' },
  { icon: 'solar:home-2-linear', category: 'home', library: 'solar', label: 'Home' },
  { icon: 'solar:home-smile-linear', category: 'home', library: 'solar', label: 'Home Smile' },
  { icon: 'solar:sofa-linear', category: 'home', library: 'solar', label: 'Sofa' },
  { icon: 'solar:chair-linear', category: 'home', library: 'solar', label: 'Chair' },
  { icon: 'solar:lamp-linear', category: 'home', library: 'solar', label: 'Lamp' },
  { icon: 'solar:bed-linear', category: 'home', library: 'solar', label: 'Bed' },
  { icon: 'solar:broom-linear', category: 'cleaning', library: 'solar', label: 'Broom' },
  { icon: 'solar:washing-machine-linear', category: 'cleaning', library: 'solar', label: 'Washing' },
  { icon: 'solar:waterdrop-linear', category: 'cleaning', library: 'solar', label: 'Water' },
  { icon: 'solar:trash-bin-trash-linear', category: 'cleaning', library: 'solar', label: 'Trash' },
  { icon: 'solar:vacuum-cleaner-linear', category: 'cleaning', library: 'solar', label: 'Vacuum' },
  { icon: 'solar:hammer-linear', category: 'repair', library: 'solar', label: 'Hammer' },
  { icon: 'solar:screwdriver-linear', category: 'repair', library: 'solar', label: 'Screwdriver' },
  { icon: 'solar:drill-linear', category: 'repair', library: 'solar', label: 'Drill' },
  { icon: 'solar:paint-roller-linear', category: 'repair', library: 'solar', label: 'Paint' },
  { icon: 'solar:plug-circle-linear', category: 'repair', library: 'solar', label: 'Electric' },
  { icon: 'solar:pipe-linear', category: 'repair', library: 'solar', label: 'Plumbing' },
  { icon: 'solar:scissors-linear', category: 'beauty', library: 'solar', label: 'Scissors' },
  { icon: 'solar:mirror-linear', category: 'beauty', library: 'solar', label: 'Mirror' },
  { icon: 'solar:perfume-linear', category: 'beauty', library: 'solar', label: 'Perfume' },
  { icon: 'solar:heart-pulse-linear', category: 'health', library: 'solar', label: 'Health' },
  { icon: 'solar:pill-linear', category: 'health', library: 'solar', label: 'Medicine' },
  { icon: 'solar:stethoscope-linear', category: 'health', library: 'solar', label: 'Doctor' },
  { icon: 'solar:laptop-linear', category: 'tech', library: 'solar', label: 'Laptop' },
  { icon: 'solar:smartphone-linear', category: 'tech', library: 'solar', label: 'Phone' },
  { icon: 'solar:monitor-linear', category: 'tech', library: 'solar', label: 'Monitor' },
  { icon: 'solar:wi-fi-router-linear', category: 'tech', library: 'solar', label: 'WiFi' },
  { icon: 'solar:camera-linear', category: 'tech', library: 'solar', label: 'Camera' },
  { icon: 'solar:air-conditioner-linear', category: 'home', library: 'solar', label: 'AC' },
  { icon: 'solar:fridge-linear', category: 'home', library: 'solar', label: 'Fridge' },
  { icon: 'solar:oven-mitts-linear', category: 'home', library: 'solar', label: 'Kitchen' },
  { icon: 'solar:car-linear', category: 'auto', library: 'solar', label: 'Car' },
  { icon: 'solar:bus-linear', category: 'auto', library: 'solar', label: 'Bus' },
  { icon: 'solar:delivery-linear', category: 'auto', library: 'solar', label: 'Delivery' },
  { icon: 'solar:shield-check-linear', category: 'other', library: 'solar', label: 'Shield' },
  { icon: 'solar:star-linear', category: 'other', library: 'solar', label: 'Star' },
  { icon: 'solar:fire-linear', category: 'other', library: 'solar', label: 'Fire' },
  { icon: 'solar:tag-price-linear', category: 'other', library: 'solar', label: 'Price Tag' },
  { icon: 'solar:calendar-linear', category: 'other', library: 'solar', label: 'Calendar' },
  { icon: 'solar:clock-circle-linear', category: 'other', library: 'solar', label: 'Clock' },
  { icon: 'solar:map-point-linear', category: 'other', library: 'solar', label: 'Location' },
  { icon: 'solar:users-group-rounded-linear', category: 'other', library: 'solar', label: 'Team' },
  { icon: 'solar:paw-linear', category: 'other', library: 'solar', label: 'Pet' },
  { icon: 'solar:leaf-linear', category: 'other', library: 'solar', label: 'Garden' },
  { icon: 'solar:sun-2-linear', category: 'other', library: 'solar', label: 'Solar' },
  { icon: 'solar:snowflake-linear', category: 'other', library: 'solar', label: 'Cooling' },
  { icon: 'solar:key-linear', category: 'other', library: 'solar', label: 'Locksmith' },
  { icon: 'solar:bug-linear', category: 'cleaning', library: 'solar', label: 'Pest Control' },
];

const hugeiconsIcons: ServiceIconOption[] = [
  { icon: 'hugeicons:home-01', category: 'home', library: 'hugeicons', label: 'Home' },
  { icon: 'hugeicons:home-02', category: 'home', library: 'hugeicons', label: 'Home Alt' },
  { icon: 'hugeicons:sofa-01', category: 'home', library: 'hugeicons', label: 'Sofa' },
  { icon: 'hugeicons:bed', category: 'home', library: 'hugeicons', label: 'Bed' },
  { icon: 'hugeicons:temperature', category: 'home', library: 'hugeicons', label: 'AC' },
  { icon: 'hugeicons:cleaning-bucket', category: 'cleaning', library: 'hugeicons', label: 'Cleaning' },
  { icon: 'hugeicons:vacuum-cleaner', category: 'cleaning', library: 'hugeicons', label: 'Vacuum' },
  { icon: 'hugeicons:body-soap', category: 'cleaning', library: 'hugeicons', label: 'Soap' },
  { icon: 'hugeicons:wrench-01', category: 'repair', library: 'hugeicons', label: 'Wrench' },
  { icon: 'hugeicons:legal-hammer', category: 'repair', library: 'hugeicons', label: 'Hammer' },
  { icon: 'hugeicons:paint-brush-01', category: 'repair', library: 'hugeicons', label: 'Paint Brush' },
  { icon: 'hugeicons:paint-bucket', category: 'repair', library: 'hugeicons', label: 'Paint Bucket' },
  { icon: 'hugeicons:electric-plugs', category: 'repair', library: 'hugeicons', label: 'Electric' },
  { icon: 'hugeicons:pipeline', category: 'repair', library: 'hugeicons', label: 'Plumbing' },
  { icon: 'hugeicons:hair-dryer', category: 'beauty', library: 'hugeicons', label: 'Hair Dryer' },
  { icon: 'hugeicons:blush-brush-01', category: 'beauty', library: 'hugeicons', label: 'Makeup Brush' },
  { icon: 'hugeicons:square-bottom-dashed-scissors', category: 'beauty', library: 'hugeicons', label: 'Scissors' },
  { icon: 'hugeicons:doctor-01', category: 'health', library: 'hugeicons', label: 'Doctor' },
  { icon: 'hugeicons:health', category: 'health', library: 'hugeicons', label: 'Health' },
  { icon: 'hugeicons:laptop', category: 'tech', library: 'hugeicons', label: 'Laptop' },
  { icon: 'hugeicons:smart-phone-01', category: 'tech', library: 'hugeicons', label: 'Phone' },
  { icon: 'hugeicons:cctv-camera', category: 'tech', library: 'hugeicons', label: 'CCTV' },
  { icon: 'hugeicons:car-01', category: 'auto', library: 'hugeicons', label: 'Car' },
  { icon: 'hugeicons:truck-delivery', category: 'auto', library: 'hugeicons', label: 'Delivery' },
  { icon: 'hugeicons:calendar-01', category: 'other', library: 'hugeicons', label: 'Calendar' },
  { icon: 'hugeicons:location-01', category: 'other', library: 'hugeicons', label: 'Location' },
  { icon: 'hugeicons:star', category: 'other', library: 'hugeicons', label: 'Star' },
  { icon: 'hugeicons:shield-01', category: 'other', library: 'hugeicons', label: 'Shield' },
];

const mdiIcons: ServiceIconOption[] = [
  { icon: 'mdi:home', category: 'home', library: 'mdi', label: 'Home' },
  { icon: 'mdi:sofa', category: 'home', library: 'mdi', label: 'Sofa' },
  { icon: 'mdi:bed', category: 'home', library: 'mdi', label: 'Bed' },
  { icon: 'mdi:fridge', category: 'home', library: 'mdi', label: 'Fridge' },
  { icon: 'mdi:ac-unit', category: 'home', library: 'mdi', label: 'AC' },
  { icon: 'mdi:cleaning', category: 'cleaning', library: 'mdi', label: 'Cleaning' },
  { icon: 'mdi:vacuum', category: 'cleaning', library: 'mdi', label: 'Vacuum' },
  { icon: 'mdi:spray-bottle', category: 'cleaning', library: 'mdi', label: 'Spray' },
  { icon: 'mdi:hammer', category: 'repair', library: 'mdi', label: 'Hammer' },
  { icon: 'mdi:wrench', category: 'repair', library: 'mdi', label: 'Wrench' },
  { icon: 'mdi:pipe-wrench', category: 'repair', library: 'mdi', label: 'Plumbing' },
  { icon: 'mdi:paint', category: 'repair', library: 'mdi', label: 'Paint' },
  { icon: 'mdi:flash', category: 'repair', library: 'mdi', label: 'Electric' },
  { icon: 'mdi:content-cut', category: 'beauty', library: 'mdi', label: 'Haircut' },
  { icon: 'mdi:hair-dryer', category: 'beauty', library: 'mdi', label: 'Hair Dryer' },
  { icon: 'mdi:scissors-cutting', category: 'beauty', library: 'mdi', label: 'Scissors' },
  { icon: 'mdi:doctor', category: 'health', library: 'mdi', label: 'Doctor' },
  { icon: 'mdi:hospital-box', category: 'health', library: 'mdi', label: 'Hospital' },
  { icon: 'mdi:laptop', category: 'tech', library: 'mdi', label: 'Laptop' },
  { icon: 'mdi:cellphone', category: 'tech', library: 'mdi', label: 'Phone' },
  { icon: 'mdi:desktop-classic', category: 'tech', library: 'mdi', label: 'Desktop' },
  { icon: 'mdi:car', category: 'auto', library: 'mdi', label: 'Car' },
  { icon: 'mdi:truck-delivery', category: 'auto', library: 'mdi', label: 'Delivery' },
  { icon: 'mdi:pets', category: 'other', library: 'mdi', label: 'Pet' },
  { icon: 'mdi:gardening', category: 'other', library: 'mdi', label: 'Garden' },
  { icon: 'mdi:shield-check', category: 'other', library: 'mdi', label: 'Shield' },
];

const lucideIcons: ServiceIconOption[] = [
  { icon: 'lucide:home', category: 'home', library: 'lucide', label: 'Home' },
  { icon: 'lucide:sofa', category: 'home', library: 'lucide', label: 'Sofa' },
  { icon: 'lucide:bed', category: 'home', library: 'lucide', label: 'Bed' },
  { icon: 'lucide:refrigerator', category: 'home', library: 'lucide', label: 'Fridge' },
  { icon: 'lucide:sparkles', category: 'cleaning', library: 'lucide', label: 'Sparkles' },
  { icon: 'lucide:spray-can', category: 'cleaning', library: 'lucide', label: 'Spray' },
  { icon: 'lucide:droplets', category: 'cleaning', library: 'lucide', label: 'Water' },
  { icon: 'lucide:wrench', category: 'repair', library: 'lucide', label: 'Wrench' },
  { icon: 'lucide:hammer', category: 'repair', library: 'lucide', label: 'Hammer' },
  { icon: 'lucide:plug', category: 'repair', library: 'lucide', label: 'Electric' },
  { icon: 'lucide:paintbrush', category: 'repair', library: 'lucide', label: 'Paint' },
  { icon: 'lucide:scissors', category: 'beauty', library: 'lucide', label: 'Scissors' },
  { icon: 'lucide:heart-pulse', category: 'health', library: 'lucide', label: 'Health' },
  { icon: 'lucide:stethoscope', category: 'health', library: 'lucide', label: 'Doctor' },
  { icon: 'lucide:laptop', category: 'tech', library: 'lucide', label: 'Laptop' },
  { icon: 'lucide:smartphone', category: 'tech', library: 'lucide', label: 'Phone' },
  { icon: 'lucide:monitor', category: 'tech', library: 'lucide', label: 'Monitor' },
  { icon: 'lucide:car', category: 'auto', library: 'lucide', label: 'Car' },
  { icon: 'lucide:truck', category: 'auto', library: 'lucide', label: 'Truck' },
  { icon: 'lucide:paw-print', category: 'other', library: 'lucide', label: 'Pet' },
  { icon: 'lucide:leaf', category: 'other', library: 'lucide', label: 'Garden' },
  { icon: 'lucide:shield-check', category: 'other', library: 'lucide', label: 'Shield' },
];

const tablerIcons: ServiceIconOption[] = [
  { icon: 'tabler:home', category: 'home', library: 'tabler', label: 'Home' },
  { icon: 'tabler:sofa', category: 'home', library: 'tabler', label: 'Sofa' },
  { icon: 'tabler:bed', category: 'home', library: 'tabler', label: 'Bed' },
  { icon: 'tabler:air-conditioning', category: 'home', library: 'tabler', label: 'AC' },
  { icon: 'tabler:vacuum-cleaner', category: 'cleaning', library: 'tabler', label: 'Vacuum' },
  { icon: 'tabler:spray', category: 'cleaning', library: 'tabler', label: 'Spray' },
  { icon: 'tabler:droplet', category: 'cleaning', library: 'tabler', label: 'Water' },
  { icon: 'tabler:tool', category: 'repair', library: 'tabler', label: 'Tool' },
  { icon: 'tabler:hammer', category: 'repair', library: 'tabler', label: 'Hammer' },
  { icon: 'tabler:plug', category: 'repair', library: 'tabler', label: 'Electric' },
  { icon: 'tabler:paint', category: 'repair', library: 'tabler', label: 'Paint' },
  { icon: 'tabler:scissors', category: 'beauty', library: 'tabler', label: 'Scissors' },
  { icon: 'tabler:heart-rate-monitor', category: 'health', library: 'tabler', label: 'Health' },
  { icon: 'tabler:stethoscope', category: 'health', library: 'tabler', label: 'Doctor' },
  { icon: 'tabler:device-laptop', category: 'tech', library: 'tabler', label: 'Laptop' },
  { icon: 'tabler:device-mobile', category: 'tech', library: 'tabler', label: 'Phone' },
  { icon: 'tabler:device-desktop', category: 'tech', library: 'tabler', label: 'Desktop' },
  { icon: 'tabler:car', category: 'auto', library: 'tabler', label: 'Car' },
  { icon: 'tabler:truck-delivery', category: 'auto', library: 'tabler', label: 'Delivery' },
  { icon: 'tabler:paw', category: 'other', library: 'tabler', label: 'Pet' },
  { icon: 'tabler:plant', category: 'other', library: 'tabler', label: 'Garden' },
  { icon: 'tabler:shield-check', category: 'other', library: 'tabler', label: 'Shield' },
];

const phosphorIcons: ServiceIconOption[] = [
  { icon: 'ph:house', category: 'home', library: 'phosphor', label: 'Home' },
  { icon: 'ph:couch', category: 'home', library: 'phosphor', label: 'Sofa' },
  { icon: 'ph:bed', category: 'home', library: 'phosphor', label: 'Bed' },
  { icon: 'ph:snowflake', category: 'home', library: 'phosphor', label: 'AC' },
  { icon: 'ph:broom', category: 'cleaning', library: 'phosphor', label: 'Broom' },
  { icon: 'ph:drop', category: 'cleaning', library: 'phosphor', label: 'Water' },
  { icon: 'ph:wrench', category: 'repair', library: 'phosphor', label: 'Wrench' },
  { icon: 'ph:hammer', category: 'repair', library: 'phosphor', label: 'Hammer' },
  { icon: 'ph:plug', category: 'repair', library: 'phosphor', label: 'Electric' },
  { icon: 'ph:paint-brush', category: 'repair', library: 'phosphor', label: 'Paint' },
  { icon: 'ph:scissors', category: 'beauty', library: 'phosphor', label: 'Scissors' },
  { icon: 'ph:heartbeat', category: 'health', library: 'phosphor', label: 'Health' },
  { icon: 'ph:stethoscope', category: 'health', library: 'phosphor', label: 'Doctor' },
  { icon: 'ph:laptop', category: 'tech', library: 'phosphor', label: 'Laptop' },
  { icon: 'ph:device-mobile', category: 'tech', library: 'phosphor', label: 'Phone' },
  { icon: 'ph:desktop', category: 'tech', library: 'phosphor', label: 'Desktop' },
  { icon: 'ph:car', category: 'auto', library: 'phosphor', label: 'Car' },
  { icon: 'ph:truck', category: 'auto', library: 'phosphor', label: 'Truck' },
  { icon: 'ph:paw-print', category: 'other', library: 'phosphor', label: 'Pet' },
  { icon: 'ph:plant', category: 'other', library: 'phosphor', label: 'Garden' },
  { icon: 'ph:shield-check', category: 'other', library: 'phosphor', label: 'Shield' },
];

export const SERVICE_ICON_OPTIONS: ServiceIconOption[] = [
  ...solarIcons,
  ...hugeiconsIcons,
  ...mdiIcons,
  ...lucideIcons,
  ...tablerIcons,
  ...phosphorIcons,
];
