sonar.projectKey=myeasyhand-customer-app
sonar.projectName=MyEasyHand Customer App
sonar.projectVersion=1.0

sonar.sources=src,app
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/coverage/**,**/.expo/**
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# sonar.organization=myeasyhand
