upstream myeasyhand_api {
    server api:5051;
    keepalive 32;
}

server {
    listen 80;
    server_name api.myeasyhand.in localhost;

    location / {
        proxy_pass http://myeasyhand_api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 90s;
    }

    location /api/docs {
        proxy_pass http://myeasyhand_api;
        proxy_set_header Host $host;
    }
}
